name: MinearchyInstruments
version: ${project.version}
main: biraw.online.bSInstruments.BSInstruments
api-version: '26.2'

commands:
  instrument:
    description: Manage instruments
    usage: /instrument <get <name>|all|mute [true|false]>
    aliases: [instruments, inst]

permissions:
  minearchyinstruments.instrument.get:
    description: Allows the player to use /instrument get
    default: op
  minearchyinstruments.instrument.all:
    description: Allows the player to use /instrument all
    default: op
  minearchyinstruments.instrument.mute:
    description: Allows the player to use /instrument mute
    default: true
