name: MinearchyInstruments
version: ${project.version}
main: biraw.online.bSInstruments.BSInstruments
api-version: '26.2'

commands:
  instrument:
    description: Manage instruments
    usage: /instrument <get <name>|song <name>|songs [all]|director|accept|stop|all|mute [true|false]>
    aliases: [instruments, inst]

permissions:
  minearchyinstruments.instrument.get:
    description: Allows the player to use /instrument get
    default: op
  minearchyinstruments.instrument.all:
    description: Allows the player to use /instrument all
    default: op
  minearchyinstruments.instrument.song:
    description: Allows the player to receive sheet music using /instrument song and /instrument songs
    default: op
  minearchyinstruments.instrument.director:
    description: Allows the player to invite nearby players to a song they are holding
    default: true
  minearchyinstruments.instrument.mute:
    description: Allows the player to use /instrument mute
    default: true
